worker.count=2

cap.service.url=http://cap.example.com
cfi.service.url=http://cfi.example.com
walking.service.url=http://walking.example.com
x.service.url=http://x.example.com
auth.service.url=http://auth.example.com/token

spring.redis.host=localhost
spring.redis.port=6379

management.endpoints.web.exposure.include=prometheus

